### ISSUE TITLE
把 Taro 项目作为一个完整分包时，如果页面中使用了Taro API，会大概率运行出错。

### ISSUE THREAD

**Issue by ywmail** [NervJS/taro-plugin-indie#3]
## 相关平台
微信小程序

小程序基础库: 2.16.0
Taro版本：3.1.2
使用框架: Vue 2.x

## 复现步骤
在config中引入这个插件，把 Taro 项目作为一个完整分包在小程序中引用：
小程序页面中，使用Taro API
```
import Taro from '@tarojs/taro';
Taro.getStorageSync(‘test’)
```
运行后，**大概率**会报如下错误：
```
VM1580:11352 页面【engine/pages/0/index]错误:
 TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_1___default.a.getStorageSync is not a function
```

## 期望结果
正常运行
## 实际结果
```
分包无法正常运行，Taro API下，不存在小程序相关的API。
```

## 可能原因分析
处理小程序的Taro API代码（`"\node_modules\@tarojs\plugin-platform-weapp\dist\runtime.js"`），在taro-loader中，被打包到app.js中了：
https://github.com/NervJS/taro/blob/next/packages/taro-loader/src/app.ts#L22-L45
处理后的Taro API实现，储存在`@tarojs/shared`中的`defaultReconciler`

使用小程序Taro API代码在`@tarojs/runtime`中：
https://github.com/NervJS/taro/blob/next/packages/taro-runtime/src/reconciler.ts#L52-L62

代码正常运行的逻辑是`@tarojs\plugin-platform-weapp\dist\runtime.js`必须要在`@tarojs/runtime`先运行。
由于`@tarojs\plugin-platform-weapp\dist\runtime.js`的代码注入在app.js中，因此要求app.js先于`@tarojs/runtime`运行。

然后小程序以分包模式加载时，页面依赖的custom-wrapper.js和comp.js，都可能在app.js先运行，custom-wrapper.js或者comp.js运行后，其依赖的`@tarojs/mini-runner/dist/template/custom-wrapper.js`先于app.js运行了`@tarojs/runtime`，导致`@tarojs/runtime先于@tarojs\plugin-platform-weapp\dist\runtime.js`运行，导致Taro API未被初始化。

正常的运行顺序：
```
taro.js loaded
app.js loaded
comp.js loaded
custom-wrapper.js loaded
```
当前出错时的运行顺序：
```
taro.js loaded
comp.js loaded
custom-wrapper.js loaded
app.js loaded
```

**Comment by Chen-jj** [comment]
的确存在此问题，感谢指出，下周我们 review 一下 PR 哈

**Comment by ywmail** [comment]
> 的确存在此问题，感谢指出，下周我们 review 一下 PR 哈

嗯嗯，感谢抽空review~

**Comment by Chen-jj** [comment]
已发 v0.0.3 进行修复，感谢贡献🙏
